### ISSUE TITLE
Deleting a feed causes the article list to be cleared until refresh.

### ISSUE THREAD

**Issue by Benson-chou** [tminions/binocularss#34]
**Describe the bug**
Deleting a feed causes the article list to be cleared until refreshes.

**To Reproduce**
1. Add two or more feeds.
2. Go to the feed view.
3. Delete one of the feeds.
4. Go to article view.
5. See that there are no articles.
6. Articles will come back after a refresh.

**Expected behavior**
After deleting a feed, only articles from that feed should disappear.

**Comment by hisbaan** [comment]
I think I know how to fix it. I will do so soon.
